kind: Deployment
apiVersion: apps/v1
metadata:
  name: basic-svc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic_svc_label
  template:
    metadata:
      labels:
        app: basic_svc_label
    spec:
      containers:
        - name: basic-svc-process
          image: saydus/ds-final-service:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5555
          env:
            - name: NAME
              value: basic_svc_server
            - name: PORT
              value: "5555"
---

apiVersion: v1
kind: Service
metadata:
  name: basic-svc-service
  labels:
    name: basic_svc_label
spec:
  ports:
    - port: 5555
      targetPort: 5555
      name: basic-svc-port
  selector:
    app: basic_svc_label
  type: LoadBalancer
