kind: Deployment
apiVersion: apps/v1
metadata:
  name: cpu-svc-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu_svc_label
  template:
    metadata:
      labels:
        app: cpu_svc_label
    spec:
      containers:
        - name: cpu-svc-process
          image: # TODO service Dockerfile
          ports:
            - containerPort: 5555
          env:
            - name: NAME
              value: cpu_svc_server
            - name: PORT
              value: 5555
---

apiVersion: v1
kind: Service
metadata:
  name: cpu-svc-service
  labels:
    name: cpu_svc_label
spec:
  ports:
    - port: 5555
      targetPort: 5555
      nodePort: 30002
      name: cpu-svc-port
  selector:
    app: cpu_svc_label
  type: NodePort
